// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1584904718);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1584904748);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1762);
user_pref("browser.cache.disk.capacity", 798720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1584904689);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1e79bb74-80f7-4976-a81b-47db2ab40aae}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1584904744908");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1584906524908");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1584904693785");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1584908293785");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1584904692");
user_pref("browser.slowStartup.averageTime", 3096);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200117190643");
user_pref("browser.startup.homepage_override.mstone", "72.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1584904690);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1584904691985");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "8d0c36d3c0154eed99fd05593c3769d1");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.2");
user_pref("extensions.lastPlatformVersion", "72.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"69f6a14b-950a-48e0-aa59-4d68ef425171\",\"formautofill@mozilla.org\":\"01ce0aa9-f439-4d35-9ab4-f092fb69af08\",\"screenshots@mozilla.org\":\"237d6566-b2e6-4c87-b047-3e687c331b77\",\"webcompat-reporter@mozilla.org\":\"6c8080b8-2c2d-44a3-ac8f-b25eee467a6a\",\"webcompat@mozilla.org\":\"5fb62678-e317-4589-94c1-877d47ec35a3\",\"default-theme@mozilla.org\":\"d50b8c07-0963-4fd9-b191-773d86814b2e\",\"google@search.mozilla.org\":\"df2a771a-5a6b-454c-bd90-5013fab23576\",\"amazondotcom@search.mozilla.org\":\"d7df97a2-31f3-4d80-9c13-8248c4f45cb4\",\"bing@search.mozilla.org\":\"ae5e8a90-eb7e-4001-84dc-dfdb3fcffefb\",\"ddg@search.mozilla.org\":\"79dc1e8b-143f-49a5-900b-3cb88dc15c69\",\"ebay@search.mozilla.org\":\"76d3849f-ea22-4a71-9c57-48ddd84e4c06\",\"twitter@search.mozilla.org\":\"96872f76-eaa2-4271-be03-fed232ace948\",\"wikipedia@search.mozilla.org\":\"886fcbdf-25fc-4bd0-b965-15a53ca7f8b3\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2c10f9f0-aab5-41d7-9e82-194ec75c5dab");
user_pref("security.sandbox.plugin.tempDirSuffix", "c29cff75-6fa7-4df8-8b7c-7334f252b446");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1584904687);
user_pref("toolkit.telemetry.cachedClientID", "d041d710-4139-4f38-8053-688a649435f4");
user_pref("toolkit.telemetry.previousBuildID", "20200117190643");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
