// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1584921297);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1584921417);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1584968896);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1584921177);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1584921537);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "US");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 20 Mar 2020 20:58:48 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1584921297);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"27066951-b8f0-44b4-b5ff-e1938c606207\",\"default-theme@mozilla.org\":\"9c17bd48-17df-4a1c-ac63-af706c90f2af\",\"google@search.mozilla.org\":\"d37f5def-add2-4f43-969b-0a2ae66408a4\",\"amazondotcom@search.mozilla.org\":\"3a474844-2487-418e-83d6-80c700f95a43\",\"bing@search.mozilla.org\":\"311ffedf-8780-4150-a605-ee690e631144\",\"ddg@search.mozilla.org\":\"1c2fa889-9b9b-456b-a017-5a73f21b636b\",\"twitter@search.mozilla.org\":\"1e545d6d-0e1d-4951-b1ad-f8bcb692cf6c\",\"wikipedia@search.mozilla.org\":\"e93c518c-b07b-495c-a379-e5c4dc226434\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1584921772);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.root.imap", "/home/viban/.thunderbird/7epg7myt.default-release/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "ce9af790-c889-4559-ba1b-f6141074b9c");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.4.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1584921772);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "b139926e-493d-405e-bd71-600a4a90764c");
user_pref("services.blocklist.pinning.checked", 1584921225);
user_pref("services.settings.clock_skew_seconds", -49);
user_pref("services.settings.last_etag", "\"1584906875355\"");
user_pref("services.settings.last_update_seconds", 1584921225);
user_pref("services.settings.main.hijack-blocklists.last_check", 1584921225);
user_pref("services.settings.main.language-dictionaries.last_check", 1584921225);
user_pref("services.settings.main.sites-classification.last_check", 1584921225);
user_pref("services.settings.security.onecrl.checked", 1584921225);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1584921772);
user_pref("toolkit.telemetry.cachedClientID", "51a2d358-b565-499b-ada8-2a76676e1717");
user_pref("toolkit.telemetry.prompted", 2);
